### ISSUE TITLE
Subscription is not working. 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/eos-forum#69] opened 2019-03-08 19:10 UTC
After subscribing to subs, it does not show up from the list of drop-downs/side-subs.

**Comment by Novusphere** [comment] 2019-03-09 01:15
I'm not able to reproduce this issue, both the side subs, and the drop down subs seem to update accordingly when subscribing/unsubscribing to subs. Note that subs are ordered alphabetically.

**Comment by bluabaleno** [comment] 2019-03-09 14:24
try subscribing to e/meatlpackagingtoken

**Comment by Novusphere** [comment] 2019-03-10 20:45
@bluabaleno https://i.imgur.com/ejwBuL2.png works fine?

**Comment by Novusphere** [comment] 2019-03-28 11:28
Fixed in conjunction with #68

**Closed by Novusphere** 2019-03-28 11:29 UTC
Labels: bug, unconfirmed / need more info
